//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÉttermiSzoftver_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enEtel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enEtel()
        {
            this.enRendelesek = new HashSet<enRendeles>();
            this.enMenuk = new HashSet<enMenu>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Ar { get; set; }
        public string Leiras { get; set; }
        public string Tipus { get; set; }
        public string KepURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enRendeles> enRendelesek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enMenu> enMenuk { get; set; }
    }
}
