//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÉttermiSzoftver_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enSzemely
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enSzemely()
        {
            this.enRendelesek = new HashSet<enRendeles>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Pozicio { get; set; }
        public string Jelszo { get; set; }
        public System.DateTime SzulDatum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enRendeles> enRendelesek { get; set; }
    }
}
